// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"skiptitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"proSnapMinimap","status":true,"description":"Minimap","parameters":{"General":"","Background":"rgba(50,120,120,1)","PlayerColor":"rgba(255,240,200,1)","EventColor":"rgba(255,255,255,1)","Outline Color":"rgba(0,0,0,1)","Fog of War Blur":"8","Disable Outline":"false","Show Compas":"false","Location":"BOTTOMRIGHT","Impassable Color":"rgba(20,35,120,1)","Enable Automatic Drawing":"true","Enable Region Drawing":"true","Use Terrain Tag":"true","Region Colors":"","Region1":"rgba(0,0,0,1)","Region2":"rgba(50,120,120,1)","Region3":"rgba(100,150,150,1)","Region4":"rgba(150,200,200,1)","Region5":"rgba(200,220,220,1)","Icons":"","Item Shop":"176","Weapon Shop":"97","Armor Shop":"137","Magic Shop":"189","Inn":"8","Bar":"4","Church":"221","Dungeon":"5","Bank":"314"}},
{"name":"OrangeHud","status":true,"description":"<OrangeHud> 2.1 - Creates a custom HUD based on the params","parameters":{"DefaultFontFace":"Verdana","DefaultFontSize":"18","DefaultFontColor":"#FFFFFF","DefaultFontItalic":"false","HudWidth":"0","HudHeight":"0","HudX":"0","HudY":"0","HudOpacity":"0","SwitchId":"0","WindowMargin":"4","WindowPadding":"18","ShowOnMap":"true","ShowOnBattle":"false","ShowOnMenu":"true","ShowOnTitle":"false","ShowUnderTintLayer":"false","AutoRefresh":"true"}},
{"name":"Johnas_Show_Hearts_WORKING","status":true,"description":"Shows the number of hearts the player has (Currently 0 - 3)","parameters":{"heartsVariable":"1"}},
{"name":"OrangeHudLine","status":false,"description":"OrangeHudLine 1.5 - Adds a new Variable to Orange Hud","parameters":{"GroupName":"main","Pattern":"%1","VariableId":"1","SwitchId":"0","X":"","Y":"","FontFace":"","FontSize":"","FontColor":"","FontItalic":"","ScriptPattern":"","VariableX":"0","VariableY":"0"}},
{"name":"OrangeHudClock","status":true,"description":"Adds a new Variable to Orange Hud","parameters":{"GroupName":"main","Pattern":"%1:%2:%3","VariableHour":"0","VariableMinute":"0","VariableSecond":"0","SwitchId":"0","X":"","Y":"","FontFace":"","FontSize":"","FontColor":"","FontItalic":"","ScriptPattern":""}},
{"name":"Johnas_Show_Attack_Telegraph","status":true,"description":"Shows the affected areas of an enemy's attacks","parameters":{"":""}},
{"name":"Shaz_TileChanger","status":true,"description":"Change tiles on map or copy tiles from another map","parameters":{}},
{"name":"Johnas_testCallingFunction","status":true,"description":"","parameters":{}},
{"name":"Pause_Menu","status":true,"description":"","parameters":{}}
];
